<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="TIGER" name="handling_Tables.Assignments_Tables" tests="1" failures="0" timestamp="07 Aug 2020 07:20:33 GMT" time="94.103" errors="1">
  <testcase name="testA" time="94.103" classname="handling_Tables.Assignments_Tables">
    <error type="org.openqa.selenium.WebDriverException" message="unknown error: MSEdge failed to start: exited normally.
  (unknown error: DevToolsActivePort file doesn&#039;t exist)
  (The process started from msedge location C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe is no longer running, so MSEdgeDriver is assuming that MSEdge has crashed.)
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;TIGER&#039;, ip: &#039;192.168.137.1&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_251&#039;
Driver info: driver.version: EdgeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x00007FF6598ED052+4051026]
	Ordinal0 [0x00007FF6597C2389+2827145]
	Ordinal0 [0x00007FF65963A43C+1221692]
	Ordinal0 [0x00007FF65959344D+537677]
	Ordinal0 [0x00007FF65958C159+508249]
	Ordinal0 [0x00007FF6595BE84A+714826]
	Ordinal0 [0x00007FF6595BBC5F+703583]
	Ordinal0 [0x00007FF659597F20+556832]
	Ordinal0 [0x00007FF659598CBE+560318]
	Ordinal0 [0x00007FF6597E01F5+2949621]
	GetHandleVerifier [0x00007FF659A30AAB+1182571]
	GetHandleVerifier [0x00007FF659A45671+1267505]
	GetHandleVerifier [0x00007FF659A31788+1185864]
	Ordinal0 [0x00007FF6597D3A1A+2898458]
	Ordinal0 [0x00007FF6597E2009+2957321]
	Ordinal0 [0x00007FF6598013E8+3085288]
	BaseThreadInitThunk [0x00007FFAAB057BD4+20]
	RtlUserThreadStart [0x00007FFAAC10CE51+33]
">
      <![CDATA[org.openqa.selenium.WebDriverException: unknown error: MSEdge failed to start: exited normally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from msedge location C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe is no longer running, so MSEdgeDriver is assuming that MSEdge has crashed.)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'TIGER', ip: '192.168.137.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_251'
Driver info: driver.version: EdgeDriver
remote stacktrace: Backtrace:
Ordinal0 [0x00007FF6598ED052+4051026]
Ordinal0 [0x00007FF6597C2389+2827145]
Ordinal0 [0x00007FF65963A43C+1221692]
Ordinal0 [0x00007FF65959344D+537677]
Ordinal0 [0x00007FF65958C159+508249]
Ordinal0 [0x00007FF6595BE84A+714826]
Ordinal0 [0x00007FF6595BBC5F+703583]
Ordinal0 [0x00007FF659597F20+556832]
Ordinal0 [0x00007FF659598CBE+560318]
Ordinal0 [0x00007FF6597E01F5+2949621]
GetHandleVerifier [0x00007FF659A30AAB+1182571]
GetHandleVerifier [0x00007FF659A45671+1267505]
GetHandleVerifier [0x00007FF659A31788+1185864]
Ordinal0 [0x00007FF6597D3A1A+2898458]
Ordinal0 [0x00007FF6597E2009+2957321]
Ordinal0 [0x00007FF6598013E8+3085288]
BaseThreadInitThunk [0x00007FFAAB057BD4+20]
RtlUserThreadStart [0x00007FFAAC10CE51+33]

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:141)
at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:96)
at handling_Tables.Assignments_Tables.testA(Assignments_Tables.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- testA -->
</testsuite> <!-- handling_Tables.Assignments_Tables -->
